jobs:
  include:
    - stage: test
      language: python
      python:
        - 3.6
      before_install:
        - cd backend
        - sudo bash azure.sh
      install:
        - pip install -r requirements.txt
        - DJANGO_SETTINGS_MODULE=backend.settings.production python manage.py makemigrations
        - DJANGO_SETTINGS_MODULE=backend.settings.production python manage.py migrate
      script:
        - DJANGO_SETTINGS_MODULE=backend.settings.production python manage.py test
    - stage: test
      language: node_js
      node_js:
        - '14'
      before_install:
        - cd frontend
      install:
        - yarn
        - npm run build
      script:
        - npm run test
notifications:
  email: false