jobs:
  include:
    - stage: test
      language: python
      python:
        - 3.6
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test
    - stage: test
      language: node_js
      node_js:
        - '14'
      before_install:
        - cd frontend
      install:
        - yarn
        - npm run build
      script:
        - npm run test
notifications:
  email: false