export const STATE_ROW_STATISTICS = [
  'confirmed',
  'active',
  'recovered',
  'deaths',
];
export const DISTRICT_ROW_STATISTICS = [
  'confirmed',
  'active',
  'recovered',
  'deceased',
];

export const MAP_TYPES = {
  COUNTRY: 'country',
  STATE: 'state',
  DISTRICT: 'district',
};

export const MAP_STATISTICS = {
  TOTAL: 0,
  PER_MILLION: 1,
  ZONE: 2,
  HOTSPOTS: 3,
};

export const MAP_VIEWS = {
  STATES: 0,
  DISTRICTS: 1,
};

export const MAPS_DIR =
  process.env.NODE_ENV === 'production' ? '/mini_maps' : '/maps';

export const MAP_META = {
  India: {
    geoDataFile: `${MAPS_DIR}/India.json`,
    mapType: MAP_TYPES.COUNTRY,
    graphObjectStates: 'india-states',
    graphObjectDistricts: 'india-districts-2019-734',
  },

  Germany: {
    geoDataFile: `${MAPS_DIR}/germany.json`,
    mapType: MAP_TYPES.COUNTRY,
    graphObjectStates: 'layer',
    graphObjectDistricts: 'india-districts-2019-734',
  },

  Italy: {
    geoDataFile: `${MAPS_DIR}/italy.json`,
    mapType: MAP_TYPES.COUNTRY,
    graphObjectStates: 'ITA_adm1',
    graphObjectDistricts: 'india-districts-2019-734',
  },

  USA: {
    geoDataFile: `${MAPS_DIR}/usa.json`,
    mapType: MAP_TYPES.COUNTRY,
    graphObjectStates: 'us',
    graphObjectDistricts: 'india-districts-2019-734',
  },

  Singapore: {
    geoDataFile: `${MAPS_DIR}/singapore.json`,
    mapType: MAP_TYPES.COUNTRY,
    graphObjectStates: 'ne',
    graphObjectDistricts: 'india-districts-2019-734',
  }
};

export const STATE_CODES = {
22:	"Maharashtra",
23:	"Jammu and Kashmir",
24:	"Punjab",
25:	"Kerala",
26:	"Rajastan",
27:	"Arunachal Pradesh",
28:	"Tripura",
29:	"Nagaland",
30:	"Meghalaya",
31:	"Uttarakhand",
32:	"West Bengal",
33:	"Andaman and Nicobar Islands",
34:	"Gujarat",
35:	"Haryana",
36:	"Odisha",
37:	"Tamil Nadu",
38:	"Manipur",
39:	"Dadra and Nagar Haveli",
40:	"Chandigarh",
41:	"Jharkhand",
42:	"Uttar Pradesh",
43:	"Karnataka",
44:	"Chhattisgarh",
45:	"Delhi",
46:	"Andhra Pradesh",
47:	"Assam",
48:	"Bihar",
49:	"Mizoram",
50:	"Himachal Pradesh",
51:	"Puducherry",
52:	"Goa",
53:	"Madhya Pradesh",
54:	"Sikkim",
55:	"Daman and Diu",
56:	"Lakshadweep",
6	:"Brandenburg",
7	:"Hessen",
8	:"Schleswig-Holstein",
9	:"Mecklenburg-Vorpommern",
10 :"Saarland",
11 :"Sachsen-Anhalt",
12 :"Nordrhein-Westfalen",
13 :"Baden-Wuerttemberg",
14 :"Bremen",
15 :"Thueringen",
16 :"Rheinland-Pfalz",
17 :"Hamburg",
18 :"Niedersachsen",
19 :"Sachsen",
20 :"Berlin",
21 :"Bayern",
133	:"P.A. Bolzano",
134	:"Emilia-Romagna",
135	:"Calabria",
136	:"Liguria",
137	:"Umbria",
138	:"Friuli-Venezia Giulia",
139	:"Sardegna",
140	:"Basilicata",
141	:"Apulia",
142	:"Molise",
143	:"Veneto",
144	:"Campania",
145	:"P.A. Trento",
146	:"Marche",
147	:"Toscana",
148	:"Valle d'Aosta",
149	:"Piemonte",
150	:"Lombardia",
151	:"Lazio",
152	:"Abruzzo",
153	:"Sicily",
3585 :"Trentino-Alto Adige",
154	:"Kentucky",
155	:"South Dakota",
156	:"Massachusetts",
157	:"Texas",
158	:"Arkansas",
159	:"Iowa",
160	:"North Dakota",
161	:"Tennessee",
162	:"Montana",
163	:"Arizona",
164	:"Oklahoma",
165	:"Maine",
166	:"Ohio",
167	:"New Mexico",
168	:"Kansas",
169	:"Alaska",
170	:"Virgin Islands",
171	:"Missouri",
172	:"California",
173	:"Washington",
174	:"Virginia",
175	:"Pennsylvania",
176	:"Vermont",
177	:"Wisconsin",
178	:"North Carolina",
179	:"Hawaii",
180	:"New Hampshire",
181	:"Nebraska",
182	:"Colorado",
183	:"Delaware",
184	:"Connecticut",
185	:"District of Columbia",
186	:"New Jersey",
187	:"Indiana",
188	:"New York",
189	:"Utah",
190	:"West Virginia",
191	:"Northern Mariana Islands",
192	:"Illinois",
193	:"Mississippi",
194	:"Georgia",
195	:"Minnesota",
196	:"Puerto Rico",
197	:"Wyoming",
198	:"Oregon",
199	:"Maryland",
200	:"Rhode Island",
201	:"Florida",
202	:"Louisiana",
203	:"Michigan",
204	:"Idaho",
205	:"Guam",
206	:"Alabama",
207	:"Nevada",
208	:"South Carolina",
};


