# Generated by Django 2.1.15 on 2020-05-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coviddata',
            fields=[
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
                ('totalcases', models.IntegerField(blank=True, db_column='TotalCases', null=True)),
                ('activecases', models.IntegerField(blank=True, db_column='ActiveCases', null=True)),
                ('recoveredcases', models.IntegerField(blank=True, db_column='RecoveredCases', null=True)),
                ('deaths', models.IntegerField(blank=True, db_column='Deaths', null=True)),
                ('newtotalcases', models.IntegerField(blank=True, db_column='NewTotalCases', null=True)),
                ('newactivecases', models.IntegerField(blank=True, db_column='NewActiveCases', null=True)),
                ('newrecoveredcases', models.IntegerField(blank=True, db_column='NewRecoveredCases', null=True)),
                ('newdeaths', models.IntegerField(blank=True, db_column='NewDeaths', null=True)),
            ],
            options={
                'db_table': 'CovidData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventid', models.AutoField(db_column='EventID', primary_key=True, serialize=False)),
                ('eventname', models.CharField(blank=True, db_column='EventName', max_length=100, null=True)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
            ],
            options={
                'db_table': 'Events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Industrydata',
            fields=[
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
                ('airlines', models.FloatField(blank=True, db_column='Airlines', null=True)),
                ('travel', models.FloatField(blank=True, db_column='Travel', null=True)),
                ('retail', models.FloatField(blank=True, db_column='Retail', null=True)),
                ('entertainment', models.FloatField(blank=True, db_column='Entertainment', null=True)),
                ('food', models.FloatField(blank=True, db_column='Food', null=True)),
            ],
            options={
                'db_table': 'IndustryData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionsHierarchy',
            fields=[
                ('regionid', models.AutoField(db_column='RegionID', primary_key=True, serialize=False)),
                ('regionname', models.CharField(blank=True, db_column='RegionName', max_length=50, null=True, unique=True)),
                ('regionlevel', models.CharField(blank=True, db_column='RegionLevel', max_length=50, null=True)),
                ('superregionid', models.IntegerField(blank=True, db_column='SuperRegionID', null=True)),
            ],
            options={
                'db_table': 'Regions_Hierarchy',
                'managed': False,
            },
        ),
    ]
